[pytest]
addopts =
    '-v'
    '-s'
    '--alluredir=allure-results'
;     '--headed'
markers =
    uat: marker for uat tests
    smoke: marker for smoke tests
    regress: marker for regression tests